name: Publish
on: []
  #release:
    #types:
      #- created
      #- edited
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      #- name: Publish package
        #run: gradle publish
        #env:
          #REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          #REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}